* Makefile updated to work with newer npm versions and to not push tags with `make push` * Fixes of test cases for zsh 5.0.8, to work around a bug.

diff --git a/bin/typex b/bin/typex
--- a/bin/typex
+++ b/bin/typex
@@ -78,55 +78,85 @@ function typex  # !! Note the non-POSIX function syntax to ensure that ksh varia
     # ---- BEGIN: NESTED HELPER FUNCTIONS
     # ---- Note that, despite being nested, they're still put in the GLOBAL namespace ON FIRST INVOCATION of the hosting function (at least in Bash).
 
+    ## -------
     # SYNOPSIS
-    #   __typex_rreadlinkchain symLink
+    #   __typex_rreadlinkchain <symLink>
     # DESCRIPTION
     #  Recursive readlink: prints the CHAIN OF SYMLINKS from the input
-    #  file to its ultimate target, one full path at a time.
+    #  file to its ultimate target, as ABSOLUTE paths, with each path on a separate
+    #  line.
     #  Only the ultimate target's path is canonical, though.
-    #  Each path is output on a line of its own.
-    # EXAMPLE
-    #     # Print the ultimate target of the `git` symlink in the $PATH.
-    #   rreadlinkchain  "$(which git)"
+    #  A broken symlink in the chain causes an error that reports the
+    #  non-existent target.
+    #  An input path that is not a symlink will print its own canonical path.
+    # LIMITATIONS
+    #   - Won't work with filenames with embedded newlines or filenames containing 
+    #     the string ' -> '.
+    # COMPATIBILITY
+    #   Fully POSIX-compliant.
+    # EXAMPLES
+    #     # Print the symlink chain of the `git` executable in the $PATH.
+    #   __typex_rreadlinkchain  "$(which git)"
+    #    # Ditto, using single-line `ls -l`-style format ('a@ -> b')
+    #   __typex_rreadlinkchain  "$(which git)" | sed -nE -e '$!{a\'$'\n''@ -> ' -e '}; p' | tr -d '\n'
     # THANKS
     #   http://stackoverflow.com/a/1116890/45375
-    function __typex_rreadlinkchain { ( # execute in *subshell* to localize the effect of `cd`
+    function __typex_rreadlinkchain { ( # execute in *subshell* to localize the effect of `cd`, ...; note: use of `function` syntax requires both `{` and `(`, unlike POSIX-style function declarations
 
-      command typeset target="$1" targetDir= targetName= CDPATH= # !! The double quotes around "$1" are REQUIRED here, due to use of `command`.
+      target=$1 targetDir= targetName= CDPATH= 
+
+      # Try to make the execution environment as predictable as possible:
+      # All commands below are invoked via `command`, so we must make sure that
+      # `command` itself is not redefined as an alias or shell function.
+      # (Note that command is too inconsistent across shells, so we don't use it.)
+      # `command` is a *builtin* in bash, dash, ksh, zsh, and some platforms do not 
+      # even have an external utility version of it (e.g, Ubuntu).
+      # `command` bypasses aliases and shell functions and also finds builtins 
+      # in bash, dash, and ksh. In zsh, option POSIX_BUILTINS must be turned on for
+      # that to happen.
+      { \unalias command; \unset -f command; } >/dev/null 2>&1
+      [ -n "$ZSH_VERSION" ] && options[POSIX_BUILTINS]=on # make zsh find *builtins* with `command` too.
       
-      # !! Since this function may run in a sourced script we guard against potentially overridden commands
-      # !! by explicitly undefining any aliases or shell functions with the names of commands we're using 
-      # !! in this function; it's OK to do that, since this function runs in a subshell.
-      # !! Note that the differing behavior of `command` and `builtin` across shells makes this the simplest solution.
-      unalias cd pwd readlink dirname basename printf 2>/dev/null
-      unset -f cd pwd readlink dirname basename printf 2>/dev/null
-
       while :; do
           # Unless the file is a symlink OR exists, we report an error - note that using `-e` with a symlink reports the *target*'s existence, not the symlink's.
-        [[ -L $target || -e $target ]] || { printf '%s\n' "typex: WARNING: '$target' does not exist." 1>&2; return 1; }
+        [ -L "$target" ] || [ -e "$target" ] || { command printf '%s\n' "ERROR: '$target' does not exist." 1>&2; return 1; }
           # !! We use `cd` to change to the target's folder
           # !! so we can correctly resolve the full dir. path.
-        cd "$(dirname -- "$target")" # note: cd "" is the same as cd . - i.e., a no-op.
+        command cd "$(command dirname -- "$target")" # note: cd "" is the same as cd . - i.e., a no-op.
         targetDir=$PWD
-        targetName=$(basename -- "$target")
-        [[ $targetName == '/' ]] && targetName='' # !! curiously, `basename /` reports `\`
+        targetName=$(command basename -- "$target")
+        [ "$targetName" = '/' ] && targetName='' # !! curiously, `basename /` returns '/'
         done=0
-        if [[ ! -L $targetName ]]; then
+        if [ ! -L "$targetName" ]; then
             # We've found the ultimate target (or the input file wasn't a symlink to begin with).
             # For the *ultimate* target we want use `pwd -P` to make sure we use the actual, physical directory,
             # (not a symlink) to get the *canonical* path.
-          targetDir=$(pwd -P)
+          targetDir=$(command pwd -P)
           done=1
         fi
-          # Print (next) path.
-        printf '%s\n' "${targetDir%/}/$targetName"
+          # Print (next) path - note that we manually resolve paths ending 
+          # in /. and /.. to make sure we have a normalized path.
+        if [ "$targetName" = '.' ]; then
+          command printf '%s\n' "${targetDir%/}"
+        elif  [ "$targetName" = '..' ]; then
+          # Caveat: something like /var/.. will resolve to /private (assuming
+          # /var@ -> /private/var), i.e. the '..' is applied AFTER canonicalization.
+          command printf '%s\n' "$(command dirname -- "${targetDir}")"
+        else
+          command printf '%s\n' "${targetDir%/}/$targetName"
+        fi
           # Exit, if we've hit the non-symlink at the end of the chain.
-        (( done )) && break 
-          # File is symlink -> continue to resolve.
-        target=$(readlink -- "$targetName")
+        [ "$done" = 1 ] && break 
+        # File is symlink -> continue to resolve.
+        # Parse `ls -l` output, which, unfortunately, is the only POSIX-compliant
+        # way to determine a symlink's target. Hypothetically, this can break with
+        # filenames containig literal ' -> ' and embedded newlines.
+        target=$(command ls -l -- "$targetName")
+        target=${target#* -> }
       done
 
     ) }
+
 
     # SYNOPSIS
     #   getFileTimestamp file [kind [outputFormat]]
@@ -556,9 +586,9 @@ EOF
           command type -ta -- "$name" 2>/dev/null | command fgrep -qx 'builtin' && isBuiltIn=1
         fi
         if (( isBuiltIn )); then
-            command printf '%-10s  %s\n' 'BUILTIN:' "$name"
-            (( all )) || { __typex_restore; return 0; }
-            found=1
+          command printf '%-10s  %s\n' 'BUILTIN:' "$name"
+          (( all )) || { __typex_restore; return 0; }
+          found=1
         fi
       fi
       # -- END: look for NON-file command forms
@@ -567,20 +597,37 @@ EOF
       files=
       if (( isExplicitPath )) || [[ $name == '.' ]]; then
         if [[ -d $name ]]; then   # directory
-          # Convert to full path (without resolving symlinks).
-          files=$(command cd "$name" && command echo "$PWD")
+          # ???
+          # # Convert to full path (without resolving symlinks YET).
+          # if [[ $name =~ /../?$ ]]; then
+          #   # !! Exception: if the path ends in /.. or /../, we DO resolve symlinks
+          #   # !! right away to avoid unexpected behavior: consider the following OSX path:
+          #   # !! /tmp/.. - it *seemingly* effectively points to /, but given that /tmp is 
+          #   # !! a symlink to /private/var, `ls /tmp/..` actually targets /private(!) - i.e., /private/var/..
+          #   # !! `ls` clearly resolves the symlink /tmp first, before applying '..' - the same goes for
+          #   # !! executing a file: running /tmp/../foo would actually look for /private/foo(!)
+          #   # !! However, `ls` doesn't actually *display* the resolved dir. path when using -d, or when targeting a file: `ls /tmp/../foo`
+          #   # !! *targets* /private/foo, but *displays path* /tmp/../foo(!)
+          #   # !! The only exception is `cd` if you don't also use -P: `cd /tmp/..` actually changes to / (whereas cd -P /tmp/.. does change to /private).
+          #   files=$(command cd -P -- "$name" && command echo "$PWD")
+          # else
+          #   files=$(command cd "$name" && command echo "$PWD")
+          # fi
+          files=$name
           # Further analysis happens below.
         elif [[ -e $name || -L $name ]]; then # file or symlink to file or special file (block device, character devie, pipe, socket) - we all treat them the same here and rely on `file` to provide type info below.
           # !! If -L $name is true, but -e $name isn't, $name is a broken (dangling) symlink.
           # !! We still proceed with inspecting the symlink itself.
           [[ ! -e $name ]] && brokenSymlink=1
           # Convert to full path (without resolving symlinks).
-          # !! Note: There is an obscure bug in ksh 93u+ when passing paths such as ../.foo to cd - it fails and complains about
-          # !! <full path>/foo (!) not existing - the '.' in '.foo' is dropped.
+          # !! Note: There is an obscure bug in ksh 93u+ when passing paths such as ../.foo to cd fails and complains about
+          # !! <full path>/foo (!) not existing - the '.' in '.foo' is mistakenly dropped.
           # !! We work around it by prepending $PWD.
-          [[ -n $KSH_VERSION && $name =~ ^'../.' ]] && name="${PWD%/}/$name"
-          files=$(command cd -- "$(command dirname -- "$name")" && command echo "${PWD%/}/")$(command basename -- "$name")
-          [[ $files =~ / ]] || { __typex_restore; return 1; } # this should never happen, except if the ksh workaround above isn't effective
+          [[ -n $KSH_VERSION && $name =~ ^'../.'. ]] && name="${PWD%/}/$name"
+          # ???
+          # files=$(command cd -- "$(command dirname -- "$name")" && command echo "${PWD%/}/")$(command basename -- "$name")
+          # [[ $files =~ / ]] || { __typex_restore; return 1; } # this should never happen, except if the ksh workaround above isn't effective
+          files=$name
           # Further analysis happens below.
         else
           : # We assume this means the path doesn't exist and report it below.
@@ -619,7 +666,7 @@ EOF
             # Print the full path and, if applicable, symlink chain.
             # Note that we always examine ALL paths, not just symlinks, because even non-symlinks
             # can have symlink components (directories) in their *path*.
-            fileLinkChain=$(__typex_rreadlinkchain "$file") # !! with a broken symlink, this will output an error message 
+            fileLinkChain=$(__typex_rreadlinkchain "$file") # !! with a broken symlink, this will output an error message
             if [[ ! $fileLinkChain =~ $'\n' ]]; then  # $file is NOT a symlink, but may contain symlinks in its path.
               trueFile=$fileLinkChain
               if [[ "$file" != "$trueFile" ]]; then # $file has at least 1 symlink component (directory) in its path.
